//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora_pensiones
    {
        public int Id_bitacora { get; set; }
        public System.DateTime Fecha_Entrada { get; set; }
        public Nullable<System.DateTime> Fecha_salida { get; set; }
        public System.TimeSpan Hora_Entrada { get; set; }
        public Nullable<System.TimeSpan> Hora_Salida { get; set; }
        public Nullable<System.TimeSpan> Tiempo_Exedido { get; set; }
        public bool Penalizacion { get; set; }
        public Nullable<decimal> Monto_Penalizacion { get; set; }
        public Nullable<int> Id_Pension { get; set; }
    
        public virtual banco_pension banco_pension { get; set; }
    }
}
