//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int Id_cliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido_paterno { get; set; }
        public string Apellido_materno { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string RFC { get; set; }
        public string Razon_Social { get; set; }
        public int Id_Vehiculo { get; set; }
    
        public virtual vehiculo vehiculo { get; set; }
    }
}
