//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class cobro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cobro()
        {
            this.banco_parking = new HashSet<banco_parking>();
        }
    
        public int ID_Tabulador { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> Tarifa_Habilitada { get; set; }
        public Nullable<bool> FormaCobro { get; set; }
        public Nullable<bool> TipoCobro { get; set; }
        public Nullable<decimal> CobroLineal_ImporteDefault { get; set; }
        public Nullable<int> CobroLineal_minDefault { get; set; }
        public Nullable<decimal> CobroLineal_Importe { get; set; }
        public Nullable<int> CobroLineal_minFrecuencia { get; set; }
        public Nullable<decimal> min_30 { get; set; }
        public Nullable<decimal> min_60 { get; set; }
        public Nullable<decimal> min_90 { get; set; }
        public Nullable<decimal> min_120 { get; set; }
        public Nullable<decimal> min_150 { get; set; }
        public Nullable<decimal> min_180 { get; set; }
        public Nullable<decimal> min_210 { get; set; }
        public Nullable<decimal> min_240 { get; set; }
        public Nullable<decimal> min_270 { get; set; }
        public Nullable<decimal> min_300 { get; set; }
        public Nullable<decimal> min_330 { get; set; }
        public Nullable<decimal> min_360 { get; set; }
        public Nullable<decimal> min_390 { get; set; }
        public Nullable<decimal> min_420 { get; set; }
        public Nullable<decimal> min_450 { get; set; }
        public Nullable<decimal> min_480 { get; set; }
        public Nullable<decimal> min_510 { get; set; }
        public Nullable<decimal> min_540 { get; set; }
        public Nullable<decimal> min_570 { get; set; }
        public Nullable<decimal> min_600 { get; set; }
        public Nullable<decimal> min_630 { get; set; }
        public Nullable<decimal> min_660 { get; set; }
        public Nullable<decimal> min_690 { get; set; }
        public Nullable<decimal> min_720 { get; set; }
        public Nullable<decimal> min_750 { get; set; }
        public Nullable<decimal> min_780 { get; set; }
        public Nullable<decimal> min_810 { get; set; }
        public Nullable<decimal> min_840 { get; set; }
        public Nullable<decimal> min_870 { get; set; }
        public Nullable<decimal> min_900 { get; set; }
        public Nullable<decimal> min_930 { get; set; }
        public Nullable<decimal> min_960 { get; set; }
        public Nullable<decimal> min_990 { get; set; }
        public Nullable<decimal> min_1020 { get; set; }
        public Nullable<decimal> min_1050 { get; set; }
        public Nullable<decimal> min_1080 { get; set; }
        public Nullable<decimal> min_1110 { get; set; }
        public Nullable<decimal> min_1140 { get; set; }
        public Nullable<decimal> min_1170 { get; set; }
        public Nullable<decimal> min_1200 { get; set; }
        public Nullable<decimal> min_1230 { get; set; }
        public Nullable<decimal> min_1260 { get; set; }
        public Nullable<decimal> min_1290 { get; set; }
        public Nullable<decimal> min_1320 { get; set; }
        public Nullable<decimal> min_1350 { get; set; }
        public Nullable<decimal> min_1380 { get; set; }
        public Nullable<decimal> min_1410 { get; set; }
        public Nullable<decimal> min_1440 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banco_parking> banco_parking { get; set; }
    }
}
