//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class configgen1
    {
        public int ID_config { get; set; }
        public bool PeriodoCobro { get; set; }
        public int Tolerancia_ingreso { get; set; }
        public int Tolerancia_proxtarifa { get; set; }
        public bool Ticket_cancel { get; set; }
        public int TCancel { get; set; }
        public bool Ticket_cortesia { get; set; }
        public int Tcortesia { get; set; }
        public bool Ticker_perdido { get; set; }
        public int Tperdido { get; set; }
        public int Multa { get; set; }
        public int Capacidad { get; set; }
        public bool Buscar_vehiculo { get; set; }
        public bool Modo_cobro { get; set; }
        public int Limpiar { get; set; }
        public string DireccionFactura { get; set; }
    }
}
