//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class cortes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cortes()
        {
            this.banco_parking = new HashSet<banco_parking>();
        }
    
        public int Id_Corte { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaCorte { get; set; }
        public Nullable<decimal> Importe_Parqueo { get; set; }
        public Nullable<decimal> Importe_Cortes { get; set; }
        public Nullable<decimal> Importe_Reportado { get; set; }
        public Nullable<bool> StatusCorte { get; set; }
        public Nullable<decimal> CorteNormal { get; set; }
        public Nullable<decimal> CorteTarifa2 { get; set; }
        public Nullable<decimal> CortePension { get; set; }
        public Nullable<decimal> CortePenalizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banco_parking> banco_parking { get; set; }
    }
}
