//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class email
    {
        public int ID_Email { get; set; }
        public string Direccion_Email { get; set; }
        public string Password { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public byte[] Url_Encabezado { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string WebSite { get; set; }
        public Nullable<int> ID_ProveedoresCorreo { get; set; }
    
        public virtual proveedorescorreo proveedorescorreo { get; set; }
    }
}
