//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PARKING_DBEntities : DbContext
    {
        public PARKING_DBEntities()
            : base("name=PARKING_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<areas_personal> areas_personal { get; set; }
        public virtual DbSet<banco_parking> banco_parking { get; set; }
        public virtual DbSet<banco_pension> banco_pension { get; set; }
        public virtual DbSet<bitacora_pensiones> bitacora_pensiones { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<cobro> cobro { get; set; }
        public virtual DbSet<config_tickets> config_tickets { get; set; }
        public virtual DbSet<configgen1> configgen1 { get; set; }
        public virtual DbSet<cortes> cortes { get; set; }
        public virtual DbSet<email> email { get; set; }
        public virtual DbSet<penalizaciones> penalizaciones { get; set; }
        public virtual DbSet<pensiones> pensiones { get; set; }
        public virtual DbSet<pensiones_unicas> pensiones_unicas { get; set; }
        public virtual DbSet<proveedorescorreo> proveedorescorreo { get; set; }
        public virtual DbSet<serviciosadicionales> serviciosadicionales { get; set; }
        public virtual DbSet<tipos_pensionesu> tipos_pensionesu { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    }
}
