//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class pensiones_unicas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pensiones_unicas()
        {
            this.banco_parking = new HashSet<banco_parking>();
        }
    
        public int ID_PensionU { get; set; }
        public string Nombre_PensionU { get; set; }
        public int ID_Tipo_PensionU { get; set; }
        public Nullable<bool> PensionU_Activa { get; set; }
        public Nullable<decimal> Precio_PensionU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banco_parking> banco_parking { get; set; }
        public virtual tipos_pensionesu tipos_pensionesu { get; set; }
    }
}
