//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviciosadicionales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public serviciosadicionales()
        {
            this.banco_parking = new HashSet<banco_parking>();
        }
    
        public int ID_ServicioAd { get; set; }
        public string ServicioAdicional { get; set; }
        public Nullable<bool> ServicioAd_Activo { get; set; }
        public Nullable<decimal> Precio_ServiciosAd { get; set; }
        public Nullable<int> Tiempo_Gracia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banco_parking> banco_parking { get; set; }
    }
}
