//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int ID_Usuario { get; set; }
        public string Privilegios { get; set; }
        public string Usuario1 { get; set; }
        public string Password { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public int ID_AreaPersonal { get; set; }
        public string Puesto { get; set; }
        public string mail_Correo { get; set; }
        public string mail_Password { get; set; }
        public Nullable<int> ID_ProveedoresCorreo { get; set; }
        public Nullable<bool> CorreoConfirmado { get; set; }
    
        public virtual areas_personal areas_personal { get; set; }
        public virtual proveedorescorreo proveedorescorreo { get; set; }
    }
}
